dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - re
    - pprint
    - gensim
    - pyldavis
    - logging
    - warnings
    - nltk
    - jieba
